"""add simulations and simulation_runs tables

Revision ID: 276accb66c04
Revises: 20d7fa647c5e
Create Date: 2026-05-05 06:53:33.023265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '276accb66c04'
down_revision: Union[str, Sequence[str], None] = '20d7fa647c5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('simulations',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('scenario_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('assumptions', sa.JSON(), server_default=sa.text("json('{}')"), nullable=False),
    sa.Column('organisation_id', sa.String(), nullable=False),
    sa.Column('app_id', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'organisation_id', 'app_id', name='uq_simulations_name_org_app'),
    sa.UniqueConstraint('scenario_id', 'organisation_id', 'app_id', name='uq_simulations_scenario_id_org_app')
    )
    op.create_index('idx_simulations_org_app', 'simulations', ['organisation_id', 'app_id'], unique=False)
    op.create_index(op.f('ix_simulations_id'), 'simulations', ['id'], unique=True)
    op.create_index(op.f('ix_simulations_pid'), 'simulations', ['pid'], unique=True)
    op.create_table('simulation_runs',
    sa.Column('simulation_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('assumptions_snapshot', sa.JSON(), server_default=sa.text("json('{}')"), nullable=False),
    sa.Column('metrics_written', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_simulation_runs_simulation_id', 'simulation_runs', ['simulation_id'], unique=False)
    op.create_index(op.f('ix_simulation_runs_id'), 'simulation_runs', ['id'], unique=True)
    op.create_index(op.f('ix_simulation_runs_pid'), 'simulation_runs', ['pid'], unique=True)
    op.create_index(op.f('ix_simulation_runs_simulation_id'), 'simulation_runs', ['simulation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_simulation_runs_simulation_id'), table_name='simulation_runs')
    op.drop_index(op.f('ix_simulation_runs_pid'), table_name='simulation_runs')
    op.drop_index(op.f('ix_simulation_runs_id'), table_name='simulation_runs')
    op.drop_index('idx_simulation_runs_simulation_id', table_name='simulation_runs')
    op.drop_table('simulation_runs')
    op.drop_index(op.f('ix_simulations_pid'), table_name='simulations')
    op.drop_index(op.f('ix_simulations_id'), table_name='simulations')
    op.drop_index('idx_simulations_org_app', table_name='simulations')
    op.drop_table('simulations')
    # ### end Alembic commands ###
