"""playground

Revision ID: f73a466bb86a
Revises: 20d7fa647c5e
Create Date: 2025-10-15 18:37:43.445871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f73a466bb86a'
down_revision: Union[str, Sequence[str], None] = '20d7fa647c5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playground_sessions',
    sa.Column('organisation_id', sa.String(), nullable=False),
    sa.Column('app_id', sa.String(), nullable=False),
    sa.Column('personalisation_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('sdk_key', sa.String(), nullable=False),
    sa.Column('session_marker', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['personalisation_id'], ['personalisations.pid'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.pid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_playground_sessions_id'), 'playground_sessions', ['id'], unique=True)
    op.create_index(op.f('ix_playground_sessions_personalisation_id'), 'playground_sessions', ['personalisation_id'], unique=False)
    op.create_index(op.f('ix_playground_sessions_pid'), 'playground_sessions', ['pid'], unique=True)
    op.create_index(op.f('ix_playground_sessions_user_id'), 'playground_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_playground_sessions_user_id'), table_name='playground_sessions')
    op.drop_index(op.f('ix_playground_sessions_pid'), table_name='playground_sessions')
    op.drop_index(op.f('ix_playground_sessions_personalisation_id'), table_name='playground_sessions')
    op.drop_index(op.f('ix_playground_sessions_id'), table_name='playground_sessions')
    op.drop_table('playground_sessions')
    # ### end Alembic commands ###
